name: FirstPluginTest
version: '1.0'
main: Spigot.FirstPluginTest
api-version: 1.19

commands:
  spawnZombie:
    aliases:
      - zombie
  spawnSkeleton:
    aliases:
      - skeleton
      -
  creative:
    description: Game mode Creative
  survival:
    description: Game mode Survival
