name: FirstPluginTest
version: '1.0'
main: Spigot.FirstPluginTest
api-version: 1.19

commands:
  spawnZombie:
    aliases:
      - zombie
  spawnSkeleton:
    aliases:
      - skeleton
  weather:
    description: Set the time to 1000
    usage: /weather
  sb:
    description: Open ScoreBoard
  hologram:
    description: Spawn a hologram
  removeholograms:
    description: Remove a hologram
  rtp:
    description: Random Teleport a player
    usage: /<command>